services:
  # Redis в качестве брокера сообщений
  redis:
    image: redis:8.0.3-alpine
    container_name: donly-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MongoDB в качестве БД
  mongodb:
    image: mongo:8.0.11
    container_name: donly-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: donly
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # MinIO в качестве S3
  minio:
    image: minio/minio:RELEASE.2025-06-13T11-33-47Z
    container_name: donly-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  # geth для локального тестирования Ethereum
  geth-dev:
    image: ethereum/client-go:alltools-v1.16.1
    container_name: donly-geth-dev
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
    volumes:
      - geth_data:/root/.ethereum
    command: >
      geth
      --dev
      --dev.period=1
      --http
      --http.addr=0.0.0.0
      --http.port=8545
      --http.api=eth,net,web3,personal,miner,debug,txpool
      --http.corsdomain="*"
      --ws
      --ws.addr=0.0.0.0
      --ws.port=8546
      --ws.api=eth,net,web3,personal,miner,debug,txpool
      --ws.origins="*"
      --allow-insecure-unlock
      --rpc.gascap=0
      --rpc.txfeecap=0
      --mine
      --miner.threads=1
    healthcheck:
      test: ["CMD", "sh", "-c", "geth attach http://localhost:8545 --exec 'eth.blockNumber' > /dev/null"]
      interval: 15s
      timeout: 10s
      retries: 5

  # Consul для service discovery
  consul:
    image: hashicorp/consul:1.21
    container_name: donly-consul
    ports:
      - "8500:8500"
    command: >
      consul agent
      -dev
      -client=0.0.0.0
      -ui
      -log-level=INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Vault для управления секретами
  vault:
    image: hashicorp/vault:1.20
    container_name: donly-vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
  mongodb_data:
  minio_data:
  geth_data:

networks:
  default:
    name: donly-network